### ISSUE TITLE
Build native android on windows fail.

### ISSUE THREAD

**Issue by davidpouit** [gameclosure/devkit2#83]
I put the screenshot here

![capture](https://cloud.githubusercontent.com/assets/7350346/5562648/c2d6f42a-8e2d-11e4-814d-6d5e2b8011b4.png)

**Comment by shindekaps** [comment]
Hi
I am facing the same issue. Can any one help me out.

**Comment by davidpouit** [comment]
Hi, I have not found any solution yet the SDK and NDK are installed and the variable path configured.

**Comment by collingreen** [comment]
I'll see if I can reproduce and fix this when I get a windows machine out again.

**Comment by AnomalyAces** [comment]
I am having the same issue

**Comment by davidpouit** [comment]
I noticed that Devkit is not able to access the NDK certainly an issues of Windows 8, I'll use it on Ubuntu, until the problem is resolved.
